FROM scratch
MAINTAINER Mikael Jenkler <info@jenkler.com>
ADD gentoo1.tar.xz /
ADD gentoo2.tar.xz /
ADD gentoo3.tar.xz /
ADD gentoo4.tar.xz /
ADD gentoo5.tar.xz /

# For systemd usage this changes to /usr/sbin/init
# Keeping it as /bin/bash for compatability with previous
CMD ["/bin/bash"]
